name: "simple-messenger"

services:
  postgres_db:
    container_name: Postgres_DB
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - Messenger

  application:
    container_name: Application
    build: "./Application/."
    volumes:
      - "./Application:/Application"
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    networks:
      - Messenger

networks:
  Messenger:
    driver: bridge